/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3d/villager_minecraft_sonic_racing_crossworlds.glb 
Author: Guilherme Navarro (https://sketchfab.com/guinavarro.al)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/villager-minecraft-sonic-racing-crossworlds-f24d56a793e54d60b4ce9e680e8cbe58
Title: Villager Minecraft (Sonic Racing: CrossWorlds)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/villager_minecraft_sonic_racing_crossworlds.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.M_Extnd04_Object_04001_Body_L_Inst} skeleton={nodes.Object_6.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/villager_minecraft_sonic_racing_crossworlds.glb')
